# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20170826_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=12)),
                ('inicio', models.DateTimeField(verbose_name='fecha de inicio')),
                ('fin_curso', models.DateTimeField(blank=None)),
            ],
        ),
    ]
